#### By Chris Stone <chris.stone@nuwavepartners.com> v0.0.3 2020-06-11T15:14:36.164Z
# See http://www.appveyor.com/docs/appveyor-yml for many more options

# Version number format
version: '{build}'

# Limit the GIT Branches
branches:
  only:
  - master
  - devel
clone_depth:

# WMF 5 is PowerShell
image: WMF 5

#Publish to PowerShell Gallery with this key
environment:
  NuGetApiKey:
    secure: jv7EiV4r5pHLuZUlhSNcneEqr149lp/dN5FXBT5un+0f1fYjAvbFjDJKJz9KTK07

# Build with this script
build_script:
- ps: ./build.ps1
