#
# Module manifest for module 'Log4PoSH'
#
# Generated by: Chris Stone <Chris@Stoneyforest.net>
#
# Generated on: 5/1/2020
#

@{

	RootModule = 'Log4PoSH.psm1'
	ModuleVersion = '0.1.3'

	GUID = 'c9899721-389d-4870-8459-9ec8e551a824'
	Author = 'Chris Stone <Chris@StoneyForest.net>'
	CompanyName = ''

	Copyright = '(c) 2020 Chris Stone <Chris@Stoneyforest.net>. All rights reserved.'
	Description = 'Log4Net Powershell Wrapper Module'
	PowerShellVersion = '2.0'

	FunctionsToExport = '*'
	CmdletsToExport = @()
	VariablesToExport = '*'
	AliasesToExport = '*'

	PrivateData = @{
	    PSData = @{

	        # Tags applied to this module. These help with module discovery in online galleries.
	        # Tags = @()

	        # A URL to the license for this module.
	        LicenseUri = 'https://github.com/chrisstone/Log4PoSH/blob/master/LICENSE'

	        # A URL to the main website for this project.
	        ProjectUri = 'https://github.com/chrisstone/Log4PoSH'

	        # A URL to an icon representing this module.
	        # IconUri = ''

	        # ReleaseNotes of this module
	        # ReleaseNotes = ''

			Prerelease = 'AutoPopulated'
	    } # End of PSData hashtable
	}
}
